on: push
name: Deploy
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Deploy
      run:  |
        npm install hexo hexo-deployer-git -g
        npm install
        git config --global user.name "leejimqiu"
        git config --global user.email "2737435522qq.com"
        hexo g -d
