on: push
name: Deploy
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      uses: leejim/action-hexo@master
      env:
        EMAIL: 273743552@qq.com
        NAME: leejimqiu
